version: '3.8'
services:
  html_devenv:
    image: zsdev-i:latest
    container_name: html_devenv
    tty: true
    stdin_open: true
    attach: false
    volumes:
    - ~/.ssh:/root/.ssh
    - ./:/workspace
